
FROM maven:3.8.5-openjdk-17 AS build


WORKDIR /app



COPY ../pom.xml .
RUN mvn dependency:go-offline


COPY ../src ./src
RUN mvn clean package -DskipTests


FROM openjdk:17-jdk-slim


WORKDIR /app


COPY --from=build /app/target/smt-1.0.0.jar app.jar


EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar","--spring.profiles.active=prod"]
