version: '3.7'

services:

  smt-app:
    container_name: smt-application
    image: vampc/smt:latest
    restart:  unless-stopped
    depends_on:
      smt-db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - nginx-proxy

  smt-db:
    image: postgres:13.0-alpine
    restart:  unless-stopped
    container_name: smt-database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=smt
      - POSTGRES_DB=smt
    networks:
      - nginx-proxy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  nginx-proxy:
    external: true


volumes:
  postgres_data: